import { create } from 'zustand';
import Taro from '@tarojs/taro';

export type Lang = 'zh' | 'en';

export const LANG_OPTIONS: Array<{ id: Lang; label: string }> = [
  { id: 'zh', label: '中文' },
  { id: 'en', label: 'English' }
];

const STORAGE_KEY = 'app-lang';

/** 核心界面级文案字典（AI 对话内容/晨报正文由大模型生成，不参与翻译） */
const zh = {
  'tab.briefing': '晨报',
  'tab.inbox': '收件箱',
  'tab.hotspot': '热点',
  'tab.calendar': '日历',
  'tab.mine': '我的',

  'app.title': '私人晨报助理',

  'common.itemCount': '项',

  'mine.avatarEdit': '点头像',
  'mine.subTitle': '订阅私人晨报助理',
  'mine.quotaTitle': '本月额度',
  'mine.quotaVoice': '🎙 语音对话',
  'mine.quotaFav': '🔖 收藏空间',
  'mine.recent': '近期动态',
  'mine.nicknamePlaceholder': '怎么称呼你',
  'mine.settingGeneral': '通用',
  'mine.nickname': '称呼',
  'mine.briefingTime': '晨报推送时间',
  'mine.briefingRemind': '晨报提醒',
  'mine.settingAi': 'AI 个性化',
  'mine.prefTags': '偏好标签',
  'mine.prefMax': '最多选 5 个',
  'mine.replyStyle': '回复偏好',
  'mine.aiMemory': 'AI 记忆',
  'mine.clear': '清空',
  'mine.hotNews': '今日热点资讯',
  'mine.settingAppearance': '外观',
  'mine.uiLang': '语言',
  'mine.uiColor': '界面颜色',
  'mine.uiSize': '界面大小',
  'mine.uiSizeSmall': '小',
  'mine.uiSizeStandard': '标准',
  'mine.uiSizeLarge': '大',
  'mine.uiSizeXlarge': '特大',
  'mine.settingAccount': '账号与合规',
  'mine.terms': '用户协议',
  'mine.privacy': '隐私政策',
  'mine.aiNotice': 'AI 服务说明',
  'mine.privacyManage': '隐私授权管理',
  'mine.manageAuth': '管理我的授权',
  'mine.service': '联系客服',
  'mine.feedback': '在线反馈',
  'mine.deleteAccount': '注销账号',
  'mine.deleteData': '删除全部数据',
  'mine.shopping': '🛒 购物清单',
  'mine.learn': '📚 语言学习',
  'mine.learnDesc': '英/日/韩 · 碎片时间学一门',

  'learn.streak': '连续打卡',
  'learn.wordsLearned': '已掌握单词',
  'learn.checkedIn': '今日已学',
  'learn.notCheckedIn': '今日未学',
  'learn.progressHint': '整体进度 {percent}% · 已完成 {done}/{total} 门课',
  'learn.done': '已掌握',
  'learn.wordsUnit': '个单词',
  'learn.moreComing': '更多语种与课程持续更新中',
  'learn.courseMissing': '课程不存在或已下架',
  'learn.backToPick': '回到课程列表重新选择',
  'learn.tapToFlip': '点卡片查看释义与例句',
  'learn.gotIt': '记住了',
  'learn.notYet': '再看看',
  'learn.sessionMastered': '本次已掌握 {count}/{total} 词',
  'learn.finishTitle': '这轮学完啦！',
  'learn.wordsMastered': '个单词已掌握',
  'learn.finishHint': '明天继续来复习一遍，记忆更牢固；连续打卡解锁更多内容',
  'learn.again': '再学一轮',
  'learn.backCourses': '返回课程',
  'learn.recommendTitle': '为你推荐',
  'learn.recommendHint': '根据你的学习进度智能生成',
  'learn.recContinue': '继续学',
  'learn.recNext': '下一步',
  'learn.recReview': '该复习了',
  'learn.goLearn': '去学习',
  'community.entryTitle': '成就与打卡社区',
  'community.entryDesc': '解锁徽章 · 晒学习动态 · 互相打气',
  'community.streakUnit': '天连续打卡',
  'community.unlockedTip': '已解锁 {unlocked}/{total} 枚成就徽章',
  'community.badgeTitle': '成就徽章',
  'community.wallTitle': '打卡墙',
  'community.postPlaceholder': '分享今天的学习心得，比如「今天记住了 10 个单词」…',
  'community.postButton': '发布',
  'community.cloudNote': '动态暂存本机，云同步即将开放',
  'mine.shoppingDesc': '记想买的东西 · 多平台比价',
  'mine.privacyNote': '隐私说明：转发的内容仅用于生成你的日程、待办与摘要，存储于境内服务器；数据删除与客服入口见上方设置区。',
  'mine.docRead': '我已阅读',
  'mine.badgeSubscribed': '订阅中',
  'mine.subDesc': '语音晨报不限次畅聊 · 收藏无限量 · 习惯记忆主动调整晨报 · 新功能优先体验',
  'mine.freeUser': '免费版用户',
  'mine.earlyBirdBadge': '早鸟会员',
  'mine.memberBadge': '订阅会员',
  'mine.priceNote': '/月 起 · 前 500 名锁价（当前：{plan}）',
  'mine.subscribe': '立即订阅',
  'mine.subscribing': '下单中…',
  'mine.unlimited': '不限量',
  'mine.memoryCount': '{n} 条记忆',
  'mine.recentEmpty': '暂无动态。与 AI 对话、浏览热点、完成待办都会记录在这里。',
  'mine.planEarlyBird': '早鸟月付',
  'mine.planMonthly': '月付',
  'mine.planYearly': '年付',
  'mine.replyConcise': '简洁',
  'mine.replyBalanced': '均衡',
  'mine.replyDetailed': '详细',
  'mine.prefTech': '科技',
  'mine.prefProductivity': '效率工具',
  'mine.prefFinance': '财经',
  'mine.prefHealth': '健康',
  'mine.prefTravel': '出行',
  'mine.prefLife': '生活',
  'mine.prefAi': 'AI',

  'ai.title': '🤖 AI 助理',
  'ai.placeholder': '输入指令，如「帮我把评审会挪到明天」',
  'ai.send': '发送',
  'ai.fallbackReply': '抱歉，我刚刚走神了，请再说一次。',

  'briefing.sectionToday': '今日日程',
  'briefing.sectionTodo': '待办',
  'briefing.sectionFav': '昨日收藏精选',
  'briefing.chatHint': '和助理说点什么，或按住麦克风说话',
  'briefing.aiTag': '— AI 生成内容，仅供参考 —',
  'briefing.inputPlaceholder': '输入指令，如「把评审会挪到明天」',
  'briefing.deepPlaceholder': '深思中：说说你在纠结什么',
  'briefing.deepToggle': '深度思考开关',
  'briefing.subscribe': '订阅',
  'briefing.subscribeHint': '订阅提醒后，每天早上 {time} 叫醒你。建议把小程序添加到「我的小程序」',
  'briefing.voiceQuota': '本月语音免费额度 {used}/{total} 条',
  'briefing.subscribedVoice': '订阅用户语音畅聊',
  'briefing.quickSchedule': '安排日程',
  'briefing.quickNote': '记一条',
  'briefing.quickDone': '完成待办',
  'briefing.quickHot': '今日热点',
  'briefing.emptyTitle': '今天还没有安排',
  'briefing.emptyHint': '去收件箱把微信消息转发进来，我帮你提取日程和待办',
  'briefing.loadFailed': '晨报加载失败',
  'briefing.voiceLimitTitle': '语音额度已用完',
  'briefing.voiceLimitContent': '本月免费语音条数已用完，订阅后不限次畅聊。',
  'briefing.goSubscribe': '去订阅',
  'briefing.subscribeWeappOnly': '微信端支持订阅消息提醒',
  'briefing.subscribeOk': '明早见！',
  'briefing.subscribeFail': '订阅失败，请稍后再试',
  'briefing.subscribeBanned': '订阅已达上限或被永久拒收，后续可在「我的」页手动开启',
  'briefing.voiceNoPlugin': '语音转写插件未配置，可先用文字输入',
  'briefing.sectionIntel': '今日情报',
  'briefing.intelRawNote': '资讯来自公开 RSS，已标注来源（AI 提炼暂不可用）',
  'briefing.intelGroupLead': '— 以下导语由 AI 生成 —',
  'briefing.intelCiteHint': '查看引用来源',
  'briefing.intelDegradedGroup': '已降级为原始资讯，未做主题归并',
  'briefing.locateBtn': '📍 定位',
  'briefing.locating': '定位中…',
  'briefing.located': '已定位：',
  'briefing.locateDenied': '未授权定位，天气仍用当前城市',
  'briefing.adaptiveBusy': '今天日程很满（{count} 项 · 约 {hours} 小时），日程已前置',
  'briefing.adaptiveFocus': '先办「{title}」',
  'briefing.adaptiveTrip': '明天有去{city}的行程，情报已关注目的地天气',
  'briefing.loadLabel': '今日日程负载 {hours} 小时 · {count} 项',
  'ai.memoryUsed': '本回复已参考 {n} 条记忆',
  'briefing.weekTitle': '本周复盘',
  'briefing.weekTodosDone': '完成待办 {n} 条',
  'briefing.weekEvents': '日程 {n} 项',
  'briefing.weekKeywords': '本周关键词',
  'library.aiFilteredNote': '以下条目由 AI 从公开资讯中筛选整理',
  'library.curator': '早报员·小晨为你筛选',
  'library.whyTitle': '为什么推荐给你',
  'common.disclaimer': '内容由 AI 整理，仅供参考，不构成任何投资建议；资讯源自公开媒体，点击标题查看原文。',
  'settings.aiFilter': 'AI 精选',
  'settings.aiFilterDesc': '关闭后资讯按时间排序，不使用 AI 筛选',
  'settings.push': '推送偏好',
  'settings.pushFreq': '推送数量',
  'settings.pushFreqLow': '较少',
  'settings.pushFreqMid': '适中',
  'settings.pushFreqHigh': '较多',
  'settings.dnd': '免打扰时段',
  'settings.moduleWeather': '天气',
  'settings.moduleEvents': '日程',
  'settings.moduleNews': '资讯',
  'settings.moduleReview': '复盘',
  'settings.weekendQuiet': '周末免打扰',
  'settings.weekendEdition': '周末轻量版',
  'settings.minorMode': '未成年人模式',
  'settings.minorModeDesc': '开启后隐藏财经与热点推送，需家长密码管理',
  'settings.parentPin': '家长密码',
  'settings.parentPinSet': '已设置家长密码',
  'settings.memoryPrivacy': '记忆仅保存在本设备，用于对话上下文与任务连续性，不用于模型训练或用户画像；关闭后停止收集并删除。',
  'subscribe.renew': '订阅即将到期，请续订以继续接收晨报提醒',
  /* ---- 竞品改进收尾：X11 未成年人横幅 / X6 周末版说明 / X3 免打扰激活 / 家长密码弹层 ---- */
  'library.minorBanner': '未成年人模式已开启',
  'settings.weekendEditionDesc': '周末晨报资讯减量，周复盘置顶展示',
  'settings.dndActive': '当前处于免打扰时段',
  'settings.pinSetTitle': '设置家长密码',
  'settings.pinVerifyTitle': '输入家长密码',
  'settings.pinReset': '重置家长密码',
  'settings.pinResetConfirm': '本机存储可被清除，该控制为辅助性质，不能替代家长的直接监督。确认重置？',
  'briefing.triviaTitle': '今日冷知识',
  'briefing.streak': '连续阅读 {n} 天',
  'briefing.weekendBanner': '周末轻量版 · 资讯已减量',
  'briefing.ttsGreeting': '早上好，你的晨报准备好了',
  'briefing.audioPlay': '听晨报',
  'briefing.audioStop': '停止播报',

  /* ---- v1.3 · AI 生成合成内容标识（P0-2 合规硬门槛，2025-09-01 强制施行）---- */
  'ai.labelText': '— AI 生成内容，仅供参考 —',
  'ai.labelAudio': '— 以下语音由 AI 合成 —',
  'ai.labelExtract': '— 由 AI 提取整理，请核对 —',
  'ai.labelSummary': '— 由 AI 摘要生成，仅供参考 —',
  'ai.audioIntro': '以下内容由 AI 生成，仅供参考。',
  'ai.metaHint': '本内容含 AI 生成标识信息',
  'ai.labelVersion': 'AI 标识规范 {version}',

  'share.title': '私人晨报助理 · 把明天，安排明白',

  'inbox.pasteTitle': '粘贴要处理的内容',
  'inbox.tabExtract': '📅 提取日程待办',
  'inbox.tabWork': '🤖 工作助手',
  'inbox.screenshot': '截图',
  'inbox.copyResult': '📋 复制结果',
  'inbox.resultTitle': '提取结果',
  'inbox.resultMeta': '点击文字可修改',
  'inbox.conflictTitle': '⚠️ 排班冲突检测',
  'inbox.historyTitle': '最近处理',
  'inbox.timePlaceholder': '时间，如 2026-09-09 10:00',

  'library.hotTitle': '今日热点',
  'library.hotHint': '按你的偏好聚合 · 标注来源',
  'library.dataUpdated': '数据更新于',
  'library.dataStale': '离线缓存 · 实时源暂时不可用',
  'library.dataSources': '来源 ',
  'library.searchGo': '搜索',
  'library.searchOnlineTitle': '联网搜索',
  'library.searchOnlineHint': '必应资讯 · 标注来源',
  'library.searchSearching': '正在联网搜索…',
  'library.searchEmpty': '没有找到相关资讯',
  'library.searchEmptyHint': '换个关键词试试；H5 预览仅过滤本地资讯，联网搜索请用小程序',
  'library.favTitle': '我的收藏',
  'library.favHint': '转发内容的 AI 摘要归档',
  'library.searchPlaceholder': '搜索热点和收藏',
  'library.feedbackSaved': '已记录，内容将更贴合你',
  'library.feedbackUp': '有用',
  'library.feedbackDown': '不感兴趣',
  'library.aiTitle': '为你精选',
  'library.aiHint': '按你的兴趣 · AI 筛选',
  'library.aiEmpty': '根据你的兴趣，从今日百余条资讯里挑出最值得看的',
  'library.aiGenerate': '✨ 生成 AI 精选',
  'library.aiRegenerate': '重新生成',
  'library.aiLoading': 'AI 正在筛选今日资讯…',
  'library.aiEdit': '设置兴趣',
  'library.aiHide': '收起',
  'library.aiLabel': '— AI 筛选结果，仅供参考 —',
  'library.aiSaved': '兴趣已保存，马上生效',
  'library.aiFail': 'AI 筛选暂不可用，稍后再试',
  'library.aiNone': '这批资讯里没有强相关内容，试试调整兴趣',
  'library.aiCustomPlaceholder': '自定义关键词，如：出海、养老',
  'library.aiInterests': '兴趣',
  'library.aiSave': '保存',

  'calendar.legendSchedule': '日程',
  'calendar.legendTodo': '待办',
  'calendar.statsTitle': '本月忙闲',
  'calendar.statsEvents': '场日程',
  'calendar.statsTodos': '项待办',
  'calendar.statsBusy': '个忙日',
  'calendar.statsPeak': '最忙星期',
  'calendar.statsEmpty': '本月还很轻松',
  'calendar.conflictCount': '今日有 {n} 处时间冲突',
  'calendar.rescheduleBtn': '一键重排',
  'calendar.rescheduleSaved': '已重排 {n} 条日程',
  'calendar.rescheduleFailed': '重排失败，请稍后再试',
  'calendar.rescheduleNoSlot': '当天没有可用空闲时段',

  'search.loading': '加载中…',
  'search.empty': '输入关键词，找回你存过的任何东西',
  'search.placeholder': '搜索日程、待办、收藏…',

  'history.title': '浏览历史',
  'history.hint': '你看过的热点资讯都会留在这里，只保存在你的手机上',

  'shopping.title': '购物清单',
  'shopping.addPlaceholder': '想买什么，如「蓝牙耳机」',
  'shopping.targetPlaceholder': '预算 ¥',
  'shopping.add': '加入清单',
  'shopping.summaryHint': '点商品可记多平台比价',
  'shopping.hint': '点记价 · 比价后可看最低',
  'shopping.bought': '已买',
  'shopping.unbought': '标记未买',

  /* ---- v1.2 · 敏感权限（C-01 麦克风 / C-02 位置 / C-03 个性化推荐）---- */
  'perm.micTitle': '需要麦克风权限',
  'perm.micBody': '用于把你「按住说话」的内容转成文字。仅在你主动按住时录音，不会在后台录音；音频仅用于本次转写，不会长期保存；你可以随时在系统设置中关闭。',
  'perm.locTitle': '需要位置权限',
  'perm.locBody': '用于获取你所在城市的天气，以及在你说「去上海出差」时自动带出目的地天气。位置信息仅用于天气查询，不会与你的日程内容关联上传；你可以随时在系统设置中关闭。',
  'perm.decline': '暂不使用',
  'perm.agree': '同意并开启',
  'perm.goSettings': '去设置开启',
  'perm.micDeniedBar': '麦克风未开启，语音输入暂不可用。',
  'perm.locDeniedBar': '位置未开启，天气将使用默认城市。',
  'perm.repeatDenied': '你已多次拒绝麦克风权限，可随时在设置中开启后使用语音输入。',
  'perm.repeatDeniedLoc': '你已多次拒绝位置权限，可随时在设置中开启后获取本地天气。',
  'perm.platformUnsupported': '当前平台不支持该设置',
  'cancel': '取消',

  /* ---- v1.2 · 语音交互（V-01~V-04）---- */
  'voice.listening': '正在聆听…',
  'voice.cancelHint': '松开取消',
  'voice.processing': '处理中…',
  'voice.autoSending': '已达 60 秒，正在发送',
  'voice.tenLeft': '还能说 10 秒…',
  'voice.cancelSent': '已取消发送',
  'voice.tooShort': '按住了？再按住说一会儿',
  'voice.autoStop': '已到最长 60 秒，自动发送',
  'voice.holdTip': '按住说话',
  'voice.noCatch': '没听清，再试一次',
  'voice.recordFail': '录音失败，请检查麦克风权限',
  'voice.asrFail': '语音识别失败，请重试',

  /* ---- v1.2 · TTS 调参（V-05 / V-07）---- */
  'tts.rateLabel': '语音播报',
  'tts.rateSlow': '慢',
  'tts.rateStandard': '标准',
  'tts.rateFast': '快',
  'tts.voiceLabel': '播报音色',
  'tts.voiceAuto': '跟随场景',
  'tts.voiceFixed': '固定音色',
  'tts.sceneBriefing': '晨报',
  'tts.sceneNews': '资讯',
  'tts.sceneLearning': '学习跟读',
  'tts.sceneNight': '夜间',

  /* ---- v1.2 · 排班先提议后执行（S-01~S-04）---- */
  'plan.cardTitle': '📅 排班方案 · {n} 项待你确认',
  'plan.cardHint': 'AI 已为你调整以下安排，勾选后才会写入日历',
  'plan.noBufferNote': '部分时段已排满，以下条目未保留 10 分钟间隙',
  'plan.approveAll': '全部批准 ({n})',
  'plan.approveChecked': '仅批准选中项 ({n})',
  'plan.savedToast': '已写入 {n} 条日程',
  'plan.abandonTitle': '放弃这次调整？',
  'plan.abandonBody': '所选日程不会被修改。',
  'plan.candidateTitle': '候选时段（点击即选）',
  'plan.busyFree': '空闲',
  'plan.busyClash': '与「{title}」冲突',
  'plan.busyCrowded': '当日已有 {n} 个日程',
  'plan.reasonEarliest': '最早可用',
  'plan.reasonHabit': '与你常用的{period}时段匹配',
  'plan.reasonBuffer': '前后留白最长',
  'plan.fullDay': '当天已排满，要不要延到次日？',
  'plan.changeTime': '点此换时段',
  'plan.periodAm': '上午',
  'plan.periodPm': '下午',

  /* ---- v1.2 · 热点资讯反馈与屏蔽（N-*）---- */
  'library.feedbackUpDone': '已为你多推这类',
  'library.feedbackDownDone': '已减少这类推荐',
  'library.undo': '撤销',
  'library.blockEntry': '不再展示此类',
  'library.blockTitle': '选择要屏蔽的内容',
  'library.blockSource': '来源',
  'library.blockTag': '话题标签',
  'library.blockToast': '已屏蔽，可在『我的』-资讯偏好中恢复',
  'library.blockSection': '资讯偏好',
  'library.blockRestore': '恢复',
  'library.blockClear': '清空屏蔽清单',
  'library.blockClearConfirm': '确定清空全部屏蔽项？',
  'library.personalOffEntry': '关闭个性化推荐',
  'library.personalOffToast': '已关闭个性化推荐，接下来只展示通用内容。可在设置中重新开启。',
  'library.adLabel': '广告',
  'library.adDivider': '以下为推广内容，与上方推荐无关',

  /* ---- v1.2 · 购物助理（P-01 及 AI 不越界话术）---- */
  'shopping.targetSet': '心理价位',
  'shopping.targetClear': '清除',
  'shopping.alertToast': '💰 降价提醒：{name} 已到 ¥{price}（你的心理价位 ¥{target}）',
  'shopping.disclaimerPrice': '我只帮你查价和汇总信息，不会替你下单或付款。',
  'shopping.disclaimerSource': '以下价格来自公开渠道，仅供参考，请以商品页面实际价格为准。',
  'shopping.priceGuard': '价保提示：部分平台支持下单后 7 天内价保，建议在下单前确认该商品的价保规则。',
  'shopping.refuseOrder': '我可以帮你查价、比价和汇总优惠，但下单付款需要你本人在购物平台完成，我不会代替你操作。',

  /* ---- v1.2 · 订阅锁价与调价（B-*）+ 记忆管理（M-*）+ 注销（C-04）---- */
  'mine.lockTitle': '早鸟锁价',
  'mine.lockBody': '早鸟锁价：你现在订阅的价格将长期有效。即使未来价格调整，你的续费价格保持不变，直至你主动取消订阅。',
  'mine.lockLose': '若你主动取消后重新订阅，将按当时的最新价格执行。',
  'mine.priceChangeTitle': '订阅价格即将调整',
  'mine.priceChangeLocked': '我们将于 {date} 起调整订阅价格。你属于早期订阅用户，续费价格不受影响，仍为 ¥{price}。如需取消，可在「我的 - 订阅管理」中操作。',
  'mine.priceChangeNew': '我们将于 {date} 起调整订阅价格，届时月付将由 ¥{old} 调整为 ¥{new}。在此之前订阅可享受当前价格。',
  'mine.memoryNotice': '关闭「使用记忆」只是暂停使用：助理不再读取或写入记忆，已保存的内容会保留。要彻底删除，请使用下方的删除或清空。',
  'mine.memorySwitch': '使用记忆',
  'mine.memorySwitchHint': '开启后，助理会记住你的偏好并在后续对话中使用',
  'mine.memoryDeleteTitle': '删除这条记忆？',
  'mine.memoryDeleteBody': '「{text}」将被永久删除，助理之后不会再使用它。',
  'mine.memoryClearTitle': '清空全部记忆',
  'mine.memoryClearConfirm': '确认清空',
  'mine.memoryClearBody': '将删除 {n} 条记忆，且无法恢复。关闭「使用记忆」不会删除这些内容，清空会。',
  'mine.memoryItemDelete': '删除',
  'mine.memoryEmpty': '暂无记忆',
  'mine.memoryMetaChat': '{date} · 来自「{snippet}」',
  'mine.memoryMetaSeed': '{date} · 初始化内置',
  'mine.personalLabel': '个性化推荐',
  'mine.personalHint': '关闭后，仅展示通用内容，不再根据你的浏览与反馈做个性化排序',
  'mine.deleteTitle': '注销账号',
  'mine.deleteWarn': '注销后，你的日程、待办、收藏、学习记录、AI 记忆将被永久删除且无法恢复。我们会在 15 个工作日内完成处理。',
  'mine.deleteInputHint': '请输入「注销」以确认',
  'mine.deleteSubmit': '提交注销申请',
  'mine.deleteDone': '注销申请已提交，我们将在 15 个工作日内完成处理。',
  'mine.deleteInputMismatch': '请输入「注销」两个字以确认',
  'mine.blockEmpty': '暂无屏蔽项',

  /* ---- v1.2 · 记忆写入 toast（M-03 / M-04）---- */
  'memory.toastOne': '已记住：{text}',
  'memory.toastMulti': '已记住 {n} 条新信息',
  'memory.undo': '撤销',
  'memory.undone': '已撤销，这条不会被记住',

  /* ---- v1.2 · 学习冻结卡与补签（L-01 / L-02）---- */
  'learn.freezeLabel': '❄️ 冻结卡 ×{n}',
  'learn.freezeGain': '连续 7 天，获得 1 张冻结卡 ❄️',
  'learn.freezeUsed': '已自动使用 1 张冻结卡，连续打卡未中断',
  'learn.freezeRule': '每连续打卡满 7 天自动获得 1 张，最多持有 2 张；漏打卡次日结算时自动消耗 1 张保住连续记录。',
  'learn.makeupBtn': '补签昨天',
  'learn.makeupToast': '已补签，连续 {n} 天',
  'learn.makeupExhausted': '本月补签已用完',
  'learn.makeupRule': '每月 1 次补签额度，可补最近 2 天内的漏打卡日，次月 1 号重置。',

  /* ---- v2.1 · 每日读晨报连续（streak 改挂晨报，增量 1）---- */
  'readStreak.today': '今日已读晨报',
  'readStreak.days': '{n} 天连续',
  'readStreak.toast': '🔥 晨报连续 {n} 天，保持住',
  'readStreak.freezeUsed': '昨天用了 1 张冻结卡，连续记录保住了',
  'readStreak.freezeGranted': '恭喜，获得 {n} 张冻结卡',
  'readStreak.cardLabel': '冻结卡 ×{n}',
  'readStreak.makeup': '{n} 天，已补签',
  'readStreak.hint': '每天读一读晨报，连续不中断',
  'readStreak.progressHint': '再停留 {s} 秒、多看 {k} 个区块，即可达成今日阅读',
  'readStreak.clearTitle': '清空晨报连续记录',
  'readStreak.clearBody': '将清空 {n} 天的晨报连续记录与冻结卡，且不可恢复。确定清空？',
  'readStreak.clearConfirm': '清空',
  'readStreak.cleared': '已清空晨报连续记录',
  'mine.readStreakTitle': '晨报连续阅读',
  'mine.readStreakValue': '{n} 天',
  'learn.streakArchived': '学习连续（已归档，不再计入主连续）',

  /* ---- v2.1 · 习惯自动守护（增量 3）---- */
  'habit.sectionTitle': '习惯守护',
  'habit.sectionHint': '开启后，习惯被日程占用时会自动腾出空闲时段。',
  'habit.autoGuard': '自动守护',
  'habit.autoGuardOn': '已开启：被占用时自动挪到空闲时段',
  'habit.autoGuardOff': '未开启：被占用时只提示，不自动改动',
  'habit.autoGuardRisk': '注意：自动守护会在未经你逐次确认时改动日程，默认关闭，开启即表示你授权本助手代为调整。',
  'habit.listTitle': '我的习惯',
  'habit.none': '暂无习惯。把常做的事设为习惯，被占用时自动腾位置。',
  'habit.addFromSchedule': '设为习惯',
  'habit.addNoSchedule': '今日暂无可设为习惯的日程',
  'habit.addedToast': '已设为习惯：{title}',
  'habit.durationLabel': '{n} 分钟',
  'habit.removeTitle': '删除习惯',
  'habit.removeBody': '确定删除习惯「{title}」吗？删除后不再自动守护。',
  'habit.removeConfirm': '删除',
  'habit.history': '守护记录',
  'habit.historyEmpty': '暂无守护记录',
  'habit.guardTitle': '习惯已守护',
  'habit.guardBarText': '「{title}」已自动挪到 {time}',
  'habit.guardBarMore': '共 {n} 项已守护',
  'habit.restore': '还原',
  'habit.restoreAll': '全部还原',
  'habit.guardedToast': '「{title}」已自动挪到 {time}',
  'habit.undo': '撤销',
  'habit.undoDone': '已还原到原时段',
  'habit.undoExpired': '已超过可撤销时间',
  'habit.undoFailed': '还原失败，请稍后再试',
  'habit.recordAuto': '自动调整',
  'habit.recordBlockedBy': '因「{title}」冲突而调整',
  'habit.proposalTitle': '需你确认的习惯调整',
  'habit.proposalHint': '「{title}」被占用，附近没有合适的空闲时段，需你确认后再调整。',
  'habit.noticeTitle': '习惯已自动调整',
  'habit.noticeBody': '「{title}」于 {date} 被占用，已自动挪到 {time}',
  'mine.habitSection': '习惯守护',

  /* ---- v1.3 · 学习三练习模块（语法/听力/口语）---- */
  'learn.tabWords': '单词',
  'learn.tabGrammar': '语法',
  'learn.tabListening': '听力',
  'learn.tabSpeaking': '口语',
  'learn.grammarFillHint': '选出正确的词，补全句子',
  'learn.next': '下一题',
  'learn.finish': '完成',
  'learn.grammarDone': '填空完成！',
  'learn.grammarEmptyTitle': '本课暂无法生成填空题',
  'learn.grammarEmptyHint': '例句或同课干扰词不足，先去单词卡学一学吧',
  'learn.correctCount': '答对 {count}/{total}',
  'learn.bestScore': '本课最高分 {score}%',
  'learn.retry': '再来一轮',
  'learn.listenHint': '点击喇叭听发音，选出中文意思',
  'learn.listenPlay': '播放',
  'learn.listenSlow': '慢速',
  'learn.listenDone': '听力完成！',
  'learn.ttsUnsupportedTitle': '当前端暂不支持该语种发音',
  'learn.ttsUnsupported': '日语/韩语发音请在 H5 端体验，微信端暂只支持英语',
  'learn.speakHint': '听示范 → 按住话筒跟读',
  'learn.speakPlay': '示范',
  'learn.speakYourTurn': '轮到你啦，按住话筒跟读',
  'learn.speakSelfCheck': '读得像吗？自己说了算',
  'learn.speakGood': '读对了',
  'learn.speakAgain': '再练一次',
  'learn.speakMatch': '相似度 {score}%',
  'learn.speakMatchGood': '很接近了，就是这样读！',
  'learn.speakMatchRetry': '有点差距，再听一遍慢慢来',
  'learn.speakSkip': '跳过这句',
  'learn.speakProgress': '已跟读 {count}/{total} 句',
  'learn.speakDone': '跟读完成！'
};

const en: Record<keyof typeof zh, string> = {
  'tab.briefing': 'Briefing',
  'tab.inbox': 'Inbox',
  'tab.hotspot': 'Hotspot',
  'tab.calendar': 'Calendar',
  'tab.mine': 'Me',

  'app.title': 'Personal Morning Assistant',

  'common.itemCount': 'items',

  'mine.avatarEdit': 'Tap avatar',
  'mine.subTitle': 'Subscribe to Personal Morning Assistant',
  'mine.quotaTitle': 'Monthly Quota',
  'mine.quotaVoice': '🎙 Voice Chat',
  'mine.quotaFav': '🔖 Saved Space',
  'mine.recent': 'Recent Activity',
  'mine.nicknamePlaceholder': 'What should I call you',
  'mine.settingGeneral': 'General',
  'mine.nickname': 'Nickname',
  'mine.briefingTime': 'Briefing Time',
  'mine.briefingRemind': 'Briefing Reminder',
  'mine.settingAi': 'AI Personalization',
  'mine.prefTags': 'Preference Tags',
  'mine.prefMax': 'Max 5',
  'mine.replyStyle': 'Reply Style',
  'mine.aiMemory': 'AI Memory',
  'mine.clear': 'Clear',
  'mine.hotNews': "Today's Hot News",
  'mine.settingAppearance': 'Appearance',
  'mine.uiLang': 'Language',
  'mine.uiColor': 'Theme Color',
  'mine.uiSize': 'UI Size',
  'mine.uiSizeSmall': 'S',
  'mine.uiSizeStandard': 'M',
  'mine.uiSizeLarge': 'L',
  'mine.uiSizeXlarge': 'XL',
  'mine.settingAccount': 'Account & Compliance',
  'mine.terms': 'Terms of Service',
  'mine.privacy': 'Privacy Policy',
  'mine.aiNotice': 'AI Service Notice',
  'mine.privacyManage': 'Privacy Management',
  'mine.manageAuth': 'Manage My Authorization',
  'mine.service': 'Contact Support',
  'mine.feedback': 'Online Feedback',
  'mine.deleteAccount': 'Delete Account',
  'mine.deleteData': 'Delete All Data',
  'mine.shopping': '🛒 Shopping List',
  'mine.learn': '📚 Language Learning',
  'mine.learnDesc': 'EN/JA/KO · learn one in spare minutes',

  'learn.streak': 'Day streak',
  'learn.wordsLearned': 'Words mastered',
  'learn.checkedIn': 'Done today',
  'learn.notCheckedIn': 'Not today',
  'learn.progressHint': '{percent}% overall · {done}/{total} courses done',
  'learn.done': 'Mastered',
  'learn.wordsUnit': 'words',
  'learn.moreComing': 'More languages & courses coming soon',
  'learn.courseMissing': 'Course missing or removed',
  'learn.backToPick': 'Back to course list',
  'learn.tapToFlip': 'Tap card for meaning & example',
  'learn.gotIt': 'Got it',
  'learn.notYet': 'Again',
  'learn.sessionMastered': '{count}/{total} words mastered this round',
  'learn.finishTitle': 'Round complete!',
  'learn.wordsMastered': 'words mastered',
  'learn.finishHint': 'Review again tomorrow to lock it in; keep your streak going',
  'learn.again': 'One more round',
  'learn.backCourses': 'Back to courses',
  'learn.recommendTitle': 'For you',
  'learn.recommendHint': 'Generated from your progress',
  'learn.recContinue': 'Continue',
  'learn.recNext': 'Next up',
  'learn.recReview': 'Review due',
  'learn.goLearn': 'Start',
  'community.entryTitle': 'Achievements & community',
  'community.entryDesc': 'Unlock badges · share progress · cheer each other',
  'community.streakUnit': 'day streak',
  'community.unlockedTip': '{unlocked}/{total} badges unlocked',
  'community.badgeTitle': 'Badges',
  'community.wallTitle': 'Check-in wall',
  'community.postPlaceholder': 'Share today\'s progress, e.g. "mastered 10 words today"…',
  'community.postButton': 'Post',
  'community.cloudNote': 'Posts are stored locally; cloud sync coming soon',
  'mine.shoppingDesc': 'Save items to buy · compare prices',
  'mine.privacyNote': 'Privacy: forwarded content is only used to generate your schedule, to-dos and summaries, stored on domestic servers; data deletion & support entries are above.',
  'mine.docRead': "I've read it",
  'mine.badgeSubscribed': 'Subscribed',
  'mine.subDesc': 'Unlimited voice briefings · unlimited saves · memory-adaptive briefings · early access to new features',
  'mine.freeUser': 'Free plan user',
  'mine.earlyBirdBadge': 'Early Bird Member',
  'mine.memberBadge': 'Subscriber',
  'mine.priceNote': '/mo starting · first 500 locked price (now: {plan})',
  'mine.subscribe': 'Subscribe Now',
  'mine.subscribing': 'Ordering…',
  'mine.unlimited': 'Unlimited',
  'mine.memoryCount': '{n} memories',
  'mine.recentEmpty': 'No recent activity. Chatting with AI, browsing hotspots and completing to-dos will be recorded here.',
  'mine.planEarlyBird': 'Early Bird Monthly',
  'mine.planMonthly': 'Monthly',
  'mine.planYearly': 'Yearly',
  'mine.replyConcise': 'Concise',
  'mine.replyBalanced': 'Balanced',
  'mine.replyDetailed': 'Detailed',
  'mine.prefTech': 'Tech',
  'mine.prefProductivity': 'Productivity',
  'mine.prefFinance': 'Finance',
  'mine.prefHealth': 'Health',
  'mine.prefTravel': 'Travel',
  'mine.prefLife': 'Lifestyle',
  'mine.prefAi': 'AI',

  'ai.title': '🤖 AI Assistant',
  'ai.placeholder': 'Type a command, e.g. "Move the review to tomorrow"',
  'ai.send': 'Send',
  'ai.fallbackReply': 'Sorry, I got distracted. Please say that again.',

  'briefing.sectionToday': "Today's Schedule",
  'briefing.sectionTodo': 'To-dos',
  'briefing.sectionFav': "Yesterday's Picks",
  'briefing.chatHint': 'Talk to me, or hold the mic to speak',
  'briefing.aiTag': '— AI-generated content, for reference only —',
  'briefing.inputPlaceholder': 'Type a command, e.g. "Move the review to tomorrow"',
  'briefing.deepPlaceholder': 'Deep thinking: tell me what you are weighing',
  'briefing.deepToggle': 'Toggle deep thinking',
  'briefing.subscribe': 'Subscribe',
  'briefing.subscribeHint': 'After subscribing, I will wake you every morning at {time}. Add this mini program to "My Mini Programs"',
  'briefing.voiceQuota': 'Free voice quota this month: {used}/{total}',
  'briefing.subscribedVoice': 'Subscribers enjoy unlimited voice chat',
  'briefing.quickSchedule': 'Schedule',
  'briefing.quickNote': 'Quick note',
  'briefing.quickDone': 'Done',
  'briefing.quickHot': 'Hotspot',
  'briefing.emptyTitle': 'Nothing scheduled today',
  'briefing.emptyHint': 'Forward messages from WeChat to Inbox and I will extract your schedule and to-dos',
  'briefing.loadFailed': 'Failed to load briefing',
  'briefing.voiceLimitTitle': 'Voice quota used up',
  'briefing.voiceLimitContent': "This month's free voice messages are used up. Subscribe for unlimited chat.",
  'briefing.goSubscribe': 'Subscribe',
  'briefing.subscribeWeappOnly': 'Subscription reminders are available on WeChat',
  'briefing.subscribeOk': 'See you tomorrow!',
  'briefing.subscribeFail': 'Subscription failed, please try again later',
  'briefing.subscribeBanned': 'Subscription limit reached or permanently declined. Re-enable it under Me anytime',
  'briefing.voiceNoPlugin': 'Voice transcription plugin not configured. Please use text input for now.',
  'briefing.sectionIntel': 'Today Briefing Intel',
  'briefing.intelRawNote': 'News from public RSS with sources labeled (AI digest temporarily unavailable)',
  'briefing.intelGroupLead': '— The lead-ins below are AI-generated —',
  'briefing.intelCiteHint': 'View citation source',
  'briefing.intelDegradedGroup': 'Fell back to raw news, no topic grouping applied',
  'briefing.locateBtn': '📍 Locate',
  'briefing.locating': 'Locating…',
  'briefing.located': 'Located: ',
  'briefing.locateDenied': 'Location denied, keeping current city',
  'briefing.adaptiveBusy': 'Busy day ahead ({count} items · ~{hours}h) — schedule moved up',
  'briefing.adaptiveFocus': 'Do "{title}" first',
  'briefing.adaptiveTrip': 'Trip to {city} tomorrow — intel now tracks destination weather',
  'briefing.loadLabel': "Today's load: {hours}h · {count} items",
  'ai.memoryUsed': 'This reply referenced {n} memories',
  'briefing.weekTitle': 'Weekly review',
  'briefing.weekTodosDone': '{n} todos done',
  'briefing.weekEvents': '{n} events',
  'briefing.weekKeywords': 'Top keywords',
  'library.aiFilteredNote': 'Curated by AI from public news sources',
  'library.curator': 'Curated for you by XiaoChen, your morning editor',
  'library.whyTitle': 'Why this was picked',
  'common.disclaimer': 'AI-curated for reference only; not investment advice. Sources: public media — tap a title for the original article.',
  'settings.aiFilter': 'AI curation',
  'settings.aiFilterDesc': 'When off, news is sorted by time without AI filtering',
  'settings.push': 'Notification preferences',
  'settings.pushFreq': 'Push volume',
  'settings.pushFreqLow': 'Low',
  'settings.pushFreqMid': 'Medium',
  'settings.pushFreqHigh': 'High',
  'settings.dnd': 'Quiet hours',
  'settings.moduleWeather': 'Weather',
  'settings.moduleEvents': 'Schedule',
  'settings.moduleNews': 'News',
  'settings.moduleReview': 'Review',
  'settings.weekendQuiet': 'Weekend quiet mode',
  'settings.weekendEdition': 'Weekend lite edition',
  'settings.minorMode': 'Minor mode',
  'settings.minorModeDesc': 'Hides finance & hot-topic pushes; managed with parent PIN',
  'settings.parentPin': 'Parent PIN',
  'settings.parentPinSet': 'Parent PIN set',
  'settings.memoryPrivacy': 'Memories stay on this device and are used only for conversation context. They are never used for model training or profiling, and are deleted when the feature is disabled.',
  'subscribe.renew': 'Subscription is expiring — renew to keep receiving morning brief alerts',
  /* ---- Competitor improvements wrap-up: X11 minor banner / X6 weekend edition desc / X3 DND active / parent PIN ---- */
  'library.minorBanner': 'Minor mode is on',
  'settings.weekendEditionDesc': 'Weekend briefs trim news and pin the weekly review',
  'settings.dndActive': 'Quiet hours are active',
  'settings.pinSetTitle': 'Set parent PIN',
  'settings.pinVerifyTitle': 'Enter parent PIN',
  'settings.pinReset': 'Reset parent PIN',
  'settings.pinResetConfirm': 'Local storage can be cleared. This control is supplementary and cannot replace direct parental supervision. Reset?',
  'briefing.triviaTitle': 'Did you know',
  'briefing.streak': '{n}-day reading streak',
  'briefing.weekendBanner': 'Weekend lite · fewer news items',
  'briefing.ttsGreeting': 'Good morning, your daily brief is ready',
  'briefing.audioPlay': 'Listen',
  'briefing.audioStop': 'Stop',

  /* ---- v1.3 · AI-generated content labeling (P0-2 compliance, mandatory since 2025-09-01) ---- */
  'ai.labelText': '— AI-generated content, for reference only —',
  'ai.labelAudio': '— The following audio is AI-synthesized —',
  'ai.labelExtract': '— Extracted and organized by AI, please verify —',
  'ai.labelSummary': '— AI-generated summary, for reference only —',
  'ai.audioIntro': 'The following content is AI-generated, for reference only.',
  'ai.metaHint': 'This content carries an AI-generated label',
  'ai.labelVersion': 'AI labeling spec {version}',

  'share.title': 'My Morning Briefing · Plan tomorrow tonight',

  'inbox.pasteTitle': 'Paste content to process',
  'inbox.tabExtract': '📅 Extract schedule & to-dos',
  'inbox.tabWork': '🤖 Work Assistant',
  'inbox.screenshot': 'Screenshot',
  'inbox.copyResult': '📋 Copy Result',
  'inbox.resultTitle': 'Extraction Result',
  'inbox.resultMeta': 'Tap text to edit',
  'inbox.conflictTitle': '⚠️ Schedule Conflict',
  'inbox.historyTitle': 'Recent',
  'inbox.timePlaceholder': 'Time, e.g. 2026-09-09 10:00',

  'library.hotTitle': "Today's Hotspot",
  'library.hotHint': 'Curated by your interests · sources labeled',
  'library.dataUpdated': 'Data updated ',
  'library.dataStale': 'offline cache · live sources unavailable',
  'library.dataSources': 'Sources: ',

  'library.searchGo': 'Search',
  'library.searchOnlineTitle': 'Web search',
  'library.searchOnlineHint': 'Bing News · sources labeled',
  'library.searchSearching': 'Searching the web…',
  'library.searchEmpty': 'No matching news found',
  'library.searchEmptyHint': 'Try another keyword; H5 preview only filters local feed, use the mini program for web search',
  'library.favTitle': 'My Saved',
  'library.favHint': 'AI-summarized archive of forwarded content',
  'library.searchPlaceholder': 'Search hotspots & saved',
  'library.feedbackSaved': 'Feedback saved, content will adapt to you',
  'library.feedbackUp': 'Useful',
  'library.feedbackDown': 'Not for me',
  'library.aiTitle': 'Picked for You',
  'library.aiHint': 'AI-curated by your interests',
  'library.aiEmpty': "Get today's most relevant stories, picked by AI from 100+ items",
  'library.aiGenerate': '✨ Generate picks',
  'library.aiRegenerate': 'Regenerate',
  'library.aiLoading': 'AI is picking stories for you…',
  'library.aiEdit': 'Edit interests',
  'library.aiHide': 'Hide',
  'library.aiLabel': '— AI curated, for reference only —',
  'library.aiSaved': 'Interests saved',
  'library.aiFail': 'AI picks unavailable, try again later',
  'library.aiNone': 'Nothing strongly relevant this round, try adjusting interests',
  'library.aiCustomPlaceholder': 'Custom keywords, e.g. AI, travel',
  'library.aiInterests': 'Interests',
  'library.aiSave': 'Save',

  'calendar.legendSchedule': 'Schedule',
  'calendar.legendTodo': 'To-dos',
  'calendar.statsTitle': 'This Month',
  'calendar.statsEvents': 'events',
  'calendar.statsTodos': 'to-dos',
  'calendar.statsBusy': 'busy days',
  'calendar.statsPeak': 'peak day',
  'calendar.statsEmpty': 'A light month',
  'calendar.conflictCount': 'Today has {n} time conflicts',
  'calendar.rescheduleBtn': 'Auto-reschedule',
  'calendar.rescheduleSaved': 'Rescheduled {n} events',
  'calendar.rescheduleFailed': 'Reschedule failed, try again later',
  'calendar.rescheduleNoSlot': 'No free slot left that day',

  'search.loading': 'Loading…',
  'search.empty': 'Search to find anything you saved',
  'search.placeholder': 'Search schedule, to-dos, saved…',

  'history.title': 'Browsing History',
  'history.hint': 'Everything you viewed stays here, only on your phone',

  'shopping.title': 'Shopping List',
  'shopping.addPlaceholder': 'What to buy, e.g. "Bluetooth earbuds"',
  'shopping.targetPlaceholder': 'Budget ¥',
  'shopping.add': 'Add to List',
  'shopping.summaryHint': 'Tap item to log multi-platform prices',
  'shopping.hint': 'Tap to log price',
  'shopping.bought': 'Bought',
  'shopping.unbought': 'Mark as not bought',

  /* ---- v1.2 · 敏感权限（C-01 麦克风 / C-02 位置 / C-03 个性化推荐）---- */
  'perm.micTitle': 'Microphone access',
  'perm.micBody': 'Used to turn what you say into text. Records only while you hold the button, never in the background; audio is used for this transcription only and not stored. You can turn it off in system settings anytime.',
  'perm.locTitle': 'Location access',
  'perm.locBody': 'Used for your city\'s weather and for destination weather when you say "business trip to Shanghai". Location is used for weather lookup only and is never linked to your schedule or uploaded. You can turn it off in system settings anytime.',
  'perm.decline': 'Not now',
  'perm.agree': 'Allow',
  'perm.goSettings': 'Open settings',
  'perm.micDeniedBar': 'Microphone is off, voice input unavailable.',
  'perm.locDeniedBar': 'Location is off, using default city.',
  'perm.repeatDenied': 'You\'ve declined microphone access several times. Enable it in settings to use voice input.',
  'perm.repeatDeniedLoc': 'You\'ve declined location access several times. Enable it in settings for local weather.',
  'perm.platformUnsupported': 'Not supported on this platform',
  'cancel': 'Cancel',

  /* ---- v1.2 · 语音交互（V-01~V-04）---- */
  'voice.listening': 'Listening…',
  'voice.cancelHint': 'Release to cancel',
  'voice.processing': 'Processing…',
  'voice.autoSending': '60s reached, sending',
  'voice.tenLeft': '10 seconds left…',
  'voice.cancelSent': 'Sending cancelled',
  'voice.tooShort': 'Hold a bit longer, please',
  'voice.autoStop': '60s limit reached, sent automatically',
  'voice.holdTip': 'Hold to talk',
  'voice.noCatch': "Didn't catch that, try again",
  'voice.recordFail': 'Recording failed — check microphone permission',
  'voice.asrFail': 'Recognition failed, please try again',

  /* ---- v1.2 · TTS 调参（V-05 / V-07）---- */
  'tts.rateLabel': 'Speech',
  'tts.rateSlow': 'Slow',
  'tts.rateStandard': 'Standard',
  'tts.rateFast': 'Fast',
  'tts.voiceLabel': 'Voice',
  'tts.voiceAuto': 'Follow scene',
  'tts.voiceFixed': 'Fixed',
  'tts.sceneBriefing': 'Briefing',
  'tts.sceneNews': 'News',
  'tts.sceneLearning': 'Learning',
  'tts.sceneNight': 'Night',

  /* ---- v1.2 · 排班先提议后执行（S-01~S-04）---- */
  'plan.cardTitle': '📅 Schedule proposal · {n} to confirm',
  'plan.cardHint': 'AI adjusted the items below; only checked ones are saved',
  'plan.noBufferNote': 'Some slots were full — items below have no 10-min gap',
  'plan.approveAll': 'Approve all ({n})',
  'plan.approveChecked': 'Approve selected ({n})',
  'plan.savedToast': '{n} events saved',
  'plan.abandonTitle': 'Discard these changes?',
  'plan.abandonBody': 'Selected events will not be changed.',
  'plan.candidateTitle': 'Alternative slots (tap to pick)',
  'plan.busyFree': 'Free',
  'plan.busyClash': 'Clashes with "{title}"',
  'plan.busyCrowded': '{n} events that day',
  'plan.reasonEarliest': 'Earliest available',
  'plan.reasonHabit': 'Matches your usual {period}',
  'plan.reasonBuffer': 'Longest free buffer',
  'plan.fullDay': 'That day is full — move to the next day?',
  'plan.changeTime': 'Change time',
  'plan.periodAm': 'morning',
  'plan.periodPm': 'afternoon',

  /* ---- v1.2 · 热点资讯反馈与屏蔽（N-*）---- */
  'library.feedbackUpDone': 'Showing more like this',
  'library.feedbackDownDone': 'Showing less like this',
  'library.undo': 'Undo',
  'library.blockEntry': 'Don\'t show this again',
  'library.blockTitle': 'Choose what to hide',
  'library.blockSource': 'Source',
  'library.blockTag': 'Topic',
  'library.blockToast': 'Hidden — restore it in Me › News preferences',
  'library.blockSection': 'News preferences',
  'library.blockRestore': 'Restore',
  'library.blockClear': 'Clear all',
  'library.blockClearConfirm': 'Clear all hidden items?',
  'library.personalOffEntry': 'Turn off personalization',
  'library.personalOffToast': 'Personalization off. Showing general content only. Turn it back on in Settings.',
  'library.adLabel': 'Ad',
  'library.adDivider': 'Below is promoted content, unrelated to the picks above',

  /* ---- v1.2 · 购物助理（P-01 及 AI 不越界话术）---- */
  'shopping.targetSet': 'Target price',
  'shopping.targetClear': 'Clear',
  'shopping.alertToast': '💰 Price alert: {name} is now ¥{price} (your target ¥{target})',
  'shopping.disclaimerPrice': 'I only compare and summarize prices; I never order or pay for you.',
  'shopping.disclaimerSource': 'Prices come from public sources and are indicative only; check the product page for the final price.',
  'shopping.priceGuard': 'Price protection: some platforms offer 7-day price protection. Check the rules before ordering.',
  'shopping.refuseOrder': 'I can compare prices and summarize deals, but you must place and pay for the order yourself.',

  /* ---- v1.2 · 订阅锁价与调价（B-*）+ 记忆管理（M-*）+ 注销（C-04）---- */
  'mine.lockTitle': 'Early-bird price lock',
  'mine.lockBody': 'Early-bird lock: the price you subscribe at stays valid. Even if prices change, your renewal price stays the same until you cancel.',
  'mine.lockLose': 'If you cancel and resubscribe later, the then-current price applies.',
  'mine.priceChangeTitle': 'Subscription price is changing',
  'mine.priceChangeLocked': 'Prices change on {date}. As an early subscriber your renewal stays ¥{price}. To cancel, go to Me › Subscription.',
  'mine.priceChangeNew': 'Prices change on {date}: monthly goes from ¥{old} to ¥{new}. Subscribe before then to keep the current price.',
  'mine.memoryNotice': 'Turning off "Use memory" only pauses it: the assistant stops reading and writing memory, and saved entries are kept. To delete them, use Delete or Clear below.',
  'mine.memorySwitch': 'Use memory',
  'mine.memorySwitchHint': 'The assistant remembers your preferences and uses them later',
  'mine.memoryDeleteTitle': 'Delete this memory?',
  'mine.memoryDeleteBody': '"{text}" will be permanently deleted and no longer used.',
  'mine.memoryClearTitle': 'Clear all memory',
  'mine.memoryClearConfirm': 'Clear',
  'mine.memoryClearBody': '{n} memories will be deleted and cannot be recovered. Turning off "Use memory" keeps them; clearing removes them.',
  'mine.memoryItemDelete': 'Delete',
  'mine.memoryEmpty': 'No memories yet',
  'mine.memoryMetaChat': '{date} · from "{snippet}"',
  'mine.memoryMetaSeed': '{date} · built-in',
  'mine.personalLabel': 'Personalization',
  'mine.personalHint': 'Off: only general content, no personalized ranking from your browsing and feedback',
  'mine.deleteTitle': 'Delete account',
  'mine.deleteWarn': 'After deletion your schedule, to-dos, collections, learning records and AI memory are permanently removed. Processing takes up to 15 business days.',
  'mine.deleteInputHint': 'Type "注销" to confirm',
  'mine.deleteSubmit': 'Submit',
  'mine.deleteDone': 'Request submitted. We will process it within 15 business days.',
  'mine.deleteInputMismatch': 'Please type "注销" to confirm',
  'mine.blockEmpty': 'Nothing blocked yet',

  /* ---- v1.2 · 记忆写入 toast（M-03 / M-04）---- */
  'memory.toastOne': 'Remembered: {text}',
  'memory.toastMulti': 'Remembered {n} new things',
  'memory.undo': 'Undo',
  'memory.undone': 'Undone, this won\'t be remembered',

  /* ---- v1.2 · 学习冻结卡与补签（L-01 / L-02）---- */
  'learn.freezeLabel': '❄️ Freeze cards ×{n}',
  'learn.freezeGain': '7 days in a row — earned 1 freeze card ❄️',
  'learn.freezeUsed': 'Used 1 freeze card automatically; your streak is safe',
  'learn.freezeRule': 'Earn 1 card every 7 consecutive days, hold at most 2. A missed day consumes 1 card automatically to keep your streak.',
  'learn.makeupBtn': 'Make up yesterday',
  'learn.makeupToast': 'Made up — {n} days in a row',
  'learn.makeupExhausted': 'No make-ups left this month',
  'learn.makeupRule': '1 make-up per month for a missed day within the last 2 days; resets on the 1st.',

  /* ---- v2.1 · Daily briefing read streak ---- */
  'readStreak.today': 'Briefing read today',
  'readStreak.days': '{n}-day streak',
  'readStreak.toast': '🔥 {n}-day briefing streak — keep it up',
  'readStreak.freezeUsed': 'Used 1 freeze card yesterday; your streak is safe',
  'readStreak.freezeGranted': 'Nice — earned {n} freeze card(s)',
  'readStreak.cardLabel': 'Freeze cards ×{n}',
  'readStreak.makeup': '{n} days, made up',
  'readStreak.hint': 'Read your briefing daily to keep the streak',
  'readStreak.progressHint': 'Stay {s}s longer and view {k} sections to complete today',
  'readStreak.clearTitle': 'Clear briefing streak',
  'readStreak.clearBody': 'This clears your {n}-day briefing streak and freeze cards. It cannot be undone. Clear?',
  'readStreak.clearConfirm': 'Clear',
  'readStreak.cleared': 'Briefing streak cleared',
  'mine.readStreakTitle': 'Briefing read streak',
  'mine.readStreakValue': '{n} days',
  'learn.streakArchived': 'Learning streak (archived, no longer counts)',

  /* ---- v2.1 · Habit auto-guard ---- */
  'habit.sectionTitle': 'Habit guard',
  'habit.sectionHint': 'When on, a habit that gets occupied is auto-moved to a free slot.',
  'habit.autoGuard': 'Auto guard',
  'habit.autoGuardOn': 'On: auto-move to a free slot when occupied',
  'habit.autoGuardOff': 'Off: only notify when occupied, never auto-change',
  'habit.autoGuardRisk': 'Note: auto guard changes your schedule without asking each time. It is off by default; turning it on authorizes this assistant to adjust for you.',
  'habit.listTitle': 'My habits',
  'habit.none': 'No habits yet. Make a recurring activity a habit and it will free up time when occupied.',
  'habit.addFromSchedule': 'Make a habit',
  'habit.addNoSchedule': 'No schedule item available to make a habit today',
  'habit.addedToast': 'Habit created: {title}',
  'habit.durationLabel': '{n} min',
  'habit.removeTitle': 'Delete habit',
  'habit.removeBody': 'Delete the habit "{title}"? It will no longer be auto-guarded.',
  'habit.removeConfirm': 'Delete',
  'habit.history': 'Guard history',
  'habit.historyEmpty': 'No guard records yet',
  'habit.guardTitle': 'Habit guarded',
  'habit.guardBarText': '"{title}" auto-moved to {time}',
  'habit.guardBarMore': '{n} guarded',
  'habit.restore': 'Restore',
  'habit.restoreAll': 'Restore all',
  'habit.guardedToast': '"{title}" auto-moved to {time}',
  'habit.undo': 'Undo',
  'habit.undoDone': 'Restored to original time',
  'habit.undoExpired': 'The undo window has passed',
  'habit.undoFailed': 'Restore failed, please try again later',
  'habit.recordAuto': 'Auto-adjusted',
  'habit.recordBlockedBy': 'Adjusted due to a clash with "{title}"',
  'habit.proposalTitle': 'Habit adjustment needs your confirmation',
  'habit.proposalHint': '"{title}" is occupied and no nearby free slot fits; please confirm to adjust.',
  'habit.noticeTitle': 'Habit auto-adjusted',
  'habit.noticeBody': '"{title}" was occupied on {date} and auto-moved to {time}',
  'mine.habitSection': 'Habit guard',

  /* ---- v1.3 · 学习三练习模块（语法/听力/口语）---- */
  'learn.tabWords': 'Words',
  'learn.tabGrammar': 'Grammar',
  'learn.tabListening': 'Listening',
  'learn.tabSpeaking': 'Speaking',
  'learn.grammarFillHint': 'Pick the right word to complete the sentence',
  'learn.next': 'Next',
  'learn.finish': 'Finish',
  'learn.grammarDone': 'Fill-in complete!',
  'learn.grammarEmptyTitle': 'No fill-in questions for this lesson yet',
  'learn.grammarEmptyHint': 'Not enough examples or same-lesson words — try the word cards first',
  'learn.correctCount': '{count}/{total} correct',
  'learn.bestScore': 'Course best: {score}%',
  'learn.retry': 'Run it again',
  'learn.listenHint': 'Tap the speaker, then pick the Chinese meaning',
  'learn.listenPlay': 'Play',
  'learn.listenSlow': 'Slow',
  'learn.listenDone': 'Listening complete!',
  'learn.ttsUnsupportedTitle': 'Pronunciation unavailable on this platform',
  'learn.ttsUnsupported': 'Try Japanese / Korean pronunciation on the H5 version; the WeChat app supports English only for now',
  'learn.speakHint': 'Listen to the model → hold the mic to repeat',
  'learn.speakPlay': 'Demo',
  'learn.speakYourTurn': 'Your turn — hold the mic and repeat',
  'learn.speakSelfCheck': 'Sound alike? You decide',
  'learn.speakGood': 'Got it right',
  'learn.speakAgain': 'Practice again',
  'learn.speakMatch': '{score}% match',
  'learn.speakMatchGood': 'Very close — that\'s exactly how to say it!',
  'learn.speakMatchRetry': 'Not quite there — replay it and take it slow',
  'learn.speakSkip': 'Skip this line',
  'learn.speakProgress': '{count}/{total} lines repeated',
  'learn.speakDone': 'Speaking complete!'
};

export type LangKey = keyof typeof zh;
export const dict: Record<Lang, Record<LangKey, string>> = { zh, en };

interface LanguageState {
  lang: Lang;
  setLang: (l: Lang) => void;
}

export const useLanguageStore = create<LanguageState>((set) => ({
  lang: 'zh',
  setLang: (l) => {
    set({ lang: l });
    try {
      Taro.setStorageSync(STORAGE_KEY, l);
    } catch (err) {
      console.warn('[LanguageStore] persist failed:', err);
    }
  }
}));

// 模块加载时恢复本地选择
try {
  const saved = Taro.getStorageSync(STORAGE_KEY) as Lang;
  if (saved === 'zh' || saved === 'en') useLanguageStore.setState({ lang: saved });
} catch (err) {
  console.warn('[LanguageStore] restore failed:', err);
}

/** 组件内取翻译函数：语言切换时自动触发重渲染；支持 {key} 参数插值 */
export function useT() {
  const lang = useLanguageStore((s) => s.lang);
  return (key: LangKey, params?: Record<string, string | number>): string => {
    let str = dict[lang][key] ?? zh[key] ?? key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        str = str.split(`{${k}}`).join(String(v));
      });
    }
    return str;
  };
}
